/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardConfigRouteImport } from './routes/dashboard/config'
import { Route as DashboardServicesServiceIdRouteImport } from './routes/dashboard/services/$serviceId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfigRoute = DashboardConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesServiceIdRoute =
  DashboardServicesServiceIdRouteImport.update({
    id: '/services/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/services/$serviceId': typeof DashboardServicesServiceIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/services/$serviceId': typeof DashboardServicesServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/services/$serviceId': typeof DashboardServicesServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/sign-in'
    | '/dashboard/config'
    | '/dashboard/'
    | '/dashboard/services/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/dashboard/config'
    | '/dashboard'
    | '/dashboard/services/$serviceId'
  id:
    | '__root__'
    | '/dashboard'
    | '/sign-in'
    | '/dashboard/config'
    | '/dashboard/'
    | '/dashboard/services/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/config': {
      id: '/dashboard/config'
      path: '/config'
      fullPath: '/dashboard/config'
      preLoaderRoute: typeof DashboardConfigRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/$serviceId': {
      id: '/dashboard/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/dashboard/services/$serviceId'
      preLoaderRoute: typeof DashboardServicesServiceIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardConfigRoute: typeof DashboardConfigRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardServicesServiceIdRoute: typeof DashboardServicesServiceIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConfigRoute: DashboardConfigRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardServicesServiceIdRoute: DashboardServicesServiceIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
